const true_sentences = [
  ["1T", "一座冰山所包含的总热能明显多于一根正在燃烧的火柴。\nYí zuò bīngshān suǒ bāohán de zǒng rènéng míngxiǎn duō yú yì gēn zhèngzài ránshāo de huǒchái."],
  ["2T", "世界上第一座核反应堆建在一个壁球场里。\nShìjiè shàng dì yī zuò hé fǎnyìngduī jiàn zài yí gè bìqiúchǎng lǐ."],
  ["3T", "产卵动物没有肚脐。\nChǎnluǎn dòngwù méiyǒu dùqí."],
  ["4T", "成年海狸在水下最多可以憋气15分钟。\nChéngnián hǎilí zài shuǐxià zuìduō kěyǐ biēqì shíwǔ fēnzhōng."],
  ["5T", "蜜蜂有5只眼睛。\nMìfēng yǒu wǔ zhī yǎnjing."],
  ["6T", "蜜蜂的飞行速度可达每小时15英里。\nMìfēng de fēixíng sùdù kě dá měi xiǎoshí shíwǔ yīnglǐ."],
  ["7T", "研究表明，蚂蚁可以举起相当于自身重量5000倍的物体。\nYánjiū biǎomíng, mǎyǐ kěyǐ jǔqǐ xiāngdāng yú zìshēn zhòngliàng wǔqiān bèi de wùtǐ."],
  ["8T", "骆驼奶不会凝固。\nLuòtuó nǎi bù huì nínggù."],
  ["9T", "一只普通的红喉蜂鸟体重小于一枚五分硬币。\nYì zhī pǔtōng de hónghóu fēngniǎo tǐzhòng xiǎo yú yì méi wǔ fēn yìngbì."],
  ["10T", "杏仁属于桃子家族。\nXìngrén shǔyú táozi jiāzú."],
  ["11T", "玻璃球弹得比橡胶球高。\nBōliqíu tán de bǐ xiàngjiāoqiú gāo."],
  ["12T", "大象不会跳跃。\nDàxiàng bú huì tiàoyuè."],
  ["13T", "从未有独生子女当选过美国总统。\nCóngwèi yǒu dúshēng zǐnǚ dāngxuǎn guò Měiguó zǒngtǒng."],
  ["14T", "在19世纪末，美国铸币局发行过2美分和3美分硬币。\nZài shíjiǔ shìjì mò, Měiguó zhùbìjú fāxíng guò èr měifēn hé sān měifēn yìngbì."],
  ["15T", "海星是唯一能把胃翻过来的动物。\nHǎixīng shì wéiyī néng bǎ wèi fān guòlái de dòngwù."],
  ["16T", "如果把金鱼养在黑暗的房间里，它最终会变白。\nRúguǒ bǎ jīnyú yǎng zài hēi'àn de fángjiān lǐ, tā zuìzhōng huì biàn bái."],
  ["17T", "海豹睡觉时，大脑有四分之三仍然保持清醒。\nHǎibào shuìjiào shí, dànǎo yǒu sì fēn zhī sān réngrán bǎochí qīngxǐng."],
  ["18T", "鳄鱼能把舌头伸得比任何动物都远。\nÈyú néng bǎ shétou shēn de bǐ rènhé dòngwù dōu yuǎn."],
  ["19T", "德克萨斯州是唯一允许居民从太空进行缺席投票的州。\nDékèsàsī zhōu shì wéiyī yǔnxǔ jūmín cóng tàikōng jìnxíng quēxí tóupiào de zhōu."],
  ["20T", "1895年纽约市的限速是每小时9英里。\nYībājiǔwǔ nián Niǔyuē shì de xiànsù shì měi xiǎoshí jiǔ yīnglǐ."],
  ["21T", "在使用水银之前，人们曾用白兰地填充温度计。\nZài shǐyòng shuǐyín zhīqián, rénmen céng yòng báilándì tiánchōng wēndùjì."],
  ["22T", "路易斯安那州是以路易十四世命名的。\nLùyìsī'ānà zhōu shì yǐ Lùyì shísì shì mìngmíng de."],
  ["23T", "自由女神像的嘴宽3英尺。\nZìyóu Nǚshénxiàng de zuǐ kuān sān yīngchǐ."],
  ["24T", "长颈鹿可以舔到自己的眼睛。\nChángjǐnglù kěyǐ tiǎn dào zìjǐ de yǎnjing."],
  ["25T", "伊利诺伊州和马萨诸塞州都有名为 Sandwich 的城镇。\nYīlìnuòyī zhōu hé Mǎsàzhūsāizhōu dōu yǒu míng wéi Sandwich de chéngzhèn."],
  ["26T", "奶牛在听音乐时会产出更多牛奶。\nNǎiniú zài tīng yīnyuè shí huì chǎnchū gèng duō niúnǎi."],
  ["27T", "亚利桑那州不实行夏令时。\nYàlìsāngnà zhōu bù shíxíng xiàlìngshí."],
  ["28T", "人体一半的红细胞每七天就会更新。\nRéntǐ yíbàn de hóngxìbāo měi qī tiān jiù huì gēngxīn."],
  ["29T", "血液约占人体体重的7%。\nXuèyè yuē zhàn réntǐ tǐzhòng de bǎifēn zhī qī."],
  ["30T", "有一种鲶鱼可以在陆地上行走。\nYǒu yì zhǒng niányú kěyǐ zài lùdì shàng xíngzǒu."],
  ["31T", "水母的身体中超过95%是水。\nShuǐmǔ de shēntǐ zhōng chāoguò jiǔshíwǔ bǎifēnzhī shì shuǐ."],
  ["32T", "一只海星一次可产出约250万个卵。\nYì zhī hǎixīng yí cì kě chǎnchū yuē èrbǎi wǔshí wàn gè luǎn."],
  ["33T", "水母没有心脏。\nShuǐmǔ méiyǒu xīnzàng."],
  ["34T", "交通信号灯是在汽车之前发明的。\nJiāotōng xìnhàodēng shì zài qìchē zhīqián fāmíng de."],
  ["35T", "打喷嚏时心脏不会短暂停止跳动。\nDǎ pēntì shí xīnzàng bú huì duǎnzàn tíngzhǐ tiàodòng."],
  ["36T", "网球是在高尔夫球之前发明的。\nWǎngqiú shì zài gāo'ěrfūqiú zhīqián fāmíng de."],
  ["37T", "洗碗机是在洗衣机之前发明的。\nXǐwǎnjī shì zài xǐyījī zhīqián fāmíng de."],
  ["38T", "在殖民时期，只有奴隶才吃龙虾。\nZài zhímín shíqī, zhǐyǒu núlì cái chī lóngxiā."],
  ["39T", "佛蒙特州的蒙彼利埃是唯一没有麦当劳的美国州府。\nFóméngtè zhōu de Měngbǐlì'āi shì wéiyī méiyǒu Màidāngláo de Měiguó zhōufǔ."],
  ["40T", "罗得岛州从未批准第十八修正案（禁酒令）。\nLuódédǎo zhōu cóngwèi pīzhǔn dì shíbā xiūzhèng'àn jǐnjiǔlìng."],
  ["41T", "俄勒冈州的建州纪念日是在情人节。\nÉluègāng zhōu de jiànzhōu jìniànrì shì zài Qíngrénjié."],
  ["42T", "骆驼每只眼睛有三层眼睑。\nLuòtuó měi zhī yǎnjing yǒu sān céng yǎnjiǎn."],
  ["43T", "儿童在春天长得更快。\nÈrtóng zài chūntiān zhǎng de gèng kuài."],
  ["44T", "金星顺时针旋转。\nJīnxīng shùnshízhēn xuánzhuǎn."],
  ["45T", "尼泊尔是唯一国旗不是长方形的国家。\nNípǎo'ěr shì wéiyī guóqí bú shì chángfāngxíng de guójiā."],
  ["46T", "猫头鹰能看见蓝色。\nMātóuyīng néng kànjiàn lánsè."],
  ["47T", "法国的陆地面积小于哥伦比亚。\nFǎguó de lùdì miànjī xiǎo yú Gēlúnbǐyà."],
  ["48T", "美国没有官方语言。\nMěiguó méiyǒu guānfāng yǔyán."],
  ["49T", "鸵鸟的眼睛比大脑还大。\nTuóniǎo de yǎnjing bǐ dànǎo háidà."],
  ["50T", "吉米·卡特是第一位出生在医院的美国总统。\nJímǐ·Kǎtè shì dì yī wèi chūshēng zài yīyuàn de Měiguó zǒngtǒng."],
  ["51T", "詹姆斯·麦迪逊是最矮的美国总统。\nZhānmǔsī·Màidíxùn shì zuì ǎi de Měiguó zǒngtǒng."],
  ["52T", "有三位美国总统被授予荣誉爵士称号。\nYǒu sān wèi Měiguó zǒngtǒng bèi shòuyǔ róngyù juéshì chēnghào."],
  ["53T", "变色龙的舌头可以伸展到身体长度的两倍。\nBiànsèlóng de shétou kěyǐ shēnzhǎn dào shēntǐ chángdù de liǎng bèi."],
  ["54T", "猎豹是唯一不能收回爪子的猫科动物。\nLièbào shì wéiyī bùnéng shōuhuí zhuǎzi de māokēdòngwù."],
  ["55T", "大肠大约有5英尺长。\nDàcháng dàyuē yǒu wǔ yīngchǐ cháng."],
  ["56T", "第一批火车在18世纪开始运行。\nDì yī pī huǒchē zài shíbā shìjì kāishǐ yùnxíng."],
  ["57T", "第一台录像机（VCR）制造于1969年。\nDì yī tái lùxiàngjī (VCR) zhìzào yú yījiǔliùjiǔ nián."],
  ["58T", "世界上大约3%的水是淡水。\nShìjiè shàng dàyuē bǎifēn zhī sān de shuǐ shì dànshuǐ."],
  ["59T", "在古埃及，一码等于从鼻子到手指尖的长度。\nZài Gǔ'āijí, yì mǎ děngyú cóng bízi dào shǒuzhǐjiān de chángdù."],
  ["60T", "蓝鲸是有史以来地球上最大的动物。\nLánjīng shì yǒushǐ yǐlái dìqiú shàng zuìdà de dòngwù."],
  ["61T", "绦虫最长可达98英尺。\nTāochóng zuìcháng kě dá jiǔshíbā yīngchǐ."],
  ["62T", "恒星中心的温度可超过华氏5000万度。\nHéngxīng zhōngxīn de wēndù kě chāoguò Huáshì wǔqiān wàn dù."],
  ["63T", "美国是第一个在战争中使用潜艇的国家。\nMěiguó shì dì yī gè zài zhànzhēng zhōng shǐyòng qiántǐng de guójiā."],
  ["64T", "只有雌性蚊子会叮咬。\nZhǐyǒu cíxìng wénzi huì dīngyǎo."],
  ["65T", "虾的心脏位于头部。\nXiā de xīnzàng wèiyú tóubù."],
  ["66T", "洪都拉斯目前是世界上谋杀率最高的国家。\nHóngdūlāsī mùqián shì shìjiè shàng móushālǜ zuìgāo de guójiā."],
  ["67T", "女性眨眼的频率比男性高。\nNǚxìng zhǎyǎn de pínlǜ bǐ nánxìng gāo."],
  ["68T", "木星的质量大约是地球的317倍。\nMùxīng de zhìliàng dàyuē shì dìqiú de sānbǎi yīshíqī bèi."]
];

const false_sentences = [
  ["1F", "一座冰山所包含的总热能明显少于一根正在燃烧的火柴。\nYí zuò bīngshān suǒ bāohán de zǒng rènéng míngxiǎn shǎo yú yì gēn zhèngzài ránshāo de huǒchái."],
  ["2F", "世界上第一座核反应堆建在一个网球场里。\nShìjiè shàng dì yī zuò hé fǎnyìngduī jiàn zài yí gè wǎngqiúchǎng lǐ."],
  ["3F", "一些产卵动物有肚脐。\nYìxiē chǎnluǎn dòngwù yǒu dùqí."],
  ["4F", "成年海狸在水下最多可以憋气45分钟。\nChéngnián hǎilí zài shuǐxià zuìduō kěyǐ biēqì sìshíwǔ fēnzhōng."],
  ["5F", "蜜蜂有3只眼睛。\nMìfēng yǒu sān zhī yǎnjing."],
  ["6F", "蜜蜂的飞行速度可达每小时35英里。\nMìfēng de fēixíng sùdù kě dá měi xiǎoshí sānshíwǔ yīnglǐ."],
  ["7F", "研究表明，蚂蚁可以举起相当于自身重量5万倍的物体。\nYánjiū biǎomíng, mǎyǐ kěyǐ jǔqǐ xiāngdāng yú zìshēn zhòngliàng wǔ wàn bèi de wùtǐ."],
  ["8F", "骆驼奶比牛奶更容易凝固。\nLuòtuó nǎi bǐ niúnǎi gèng róngyì nínggù."],
  ["9F", "一只普通的红喉蜂鸟的体重相当于3枚五分硬币。\nYì zhī pǔtōng de hónghóu fēngniǎo de tǐzhòng xiāngdāng yú sān méi wǔ fēn yìngbì."],
  ["10F", "杏仁属于苹果家族。\nXìngrén shǔyú píngguǒ jiāzú."],
  ["11F", "橡胶球弹得比玻璃球高。\nXiàngjiāoqiú tán de bǐ bōliqíu gāo."],
  ["12F", "大象跳得比人类高。\nDàxiàng tiào de bǐ rénlèi gāo."],
  ["13F", "有14位美国总统是独生子女。\nYǒu shísì wèi Měiguó zǒngtǒng shì dúshēng zǐnǚ."],
  ["14F", "在19世纪末，美国铸币局发行过2美分和3美分硬币。\nZài shíjiǔ shìjì mò, Měiguó zhùbìjú fāxíng guò èr měifēn hé sān měifēn yìngbì."],
  ["15F", "小丑鱼是唯一能把胃翻过来的动物。\nXiǎochǒuyú shì wéiyī néng bǎ wèi fān guòlái de dòngwù."],
  ["16F", "如果把金鱼养在黑暗的房间里，它最终会变黑。\nRúguǒ bǎ jīnyú yǎng zài hēi'àn de fángjiān lǐ, tā zuìzhōng huì biàn hēi."],
  ["17F", "海豹睡觉时，大脑有四分之三仍然保持清醒。\nHǎibào shuìjiào shí, dànǎo yǒu sì fēn zhī sān réngrán bǎochí qīngxǐng."],
  ["18F", "鳄鱼不能伸出舌头。\nÈyú bùnéng shēn chū shétou."],
  ["19F", "阿拉巴马州是唯一允许居民从太空进行缺席投票的州。\nĀlābāmǎ zhōu shì wéiyī yǔnxǔ jūmín cóng tàikōng jìnxíng quēxí tóupiào de zhōu."],
  ["20F", "1895年纽约市的限速是每小时15英里。\nYībājiǔwǔ nián Niǔyuē shì de xiànsù shì měi xiǎoshí shíwǔ yīnglǐ."],
  ["21F", "在使用水银之前，人们曾用威士忌填充温度计。\nZài shǐyòng shuǐyín zhīqián, rénmen céng yòng wēishìjì tiánchōng wēndùjì."],
  ["22F", "路易斯安那州是以路易十六世命名的。\nLùyìsī'ānà zhōu shì yǐ Lùyì shíliù shì mìngmíng de."],
  ["23F", "自由女神像的嘴宽7英尺。\nZìyóu Nǚshénxiàng de zuǐ kuān qī yīngchǐ."],
  ["24F", "袋鼠可以舔到自己的眼睛。\nDàishǔ kěyǐ tiǎn dào zìjǐ de yǎnjing."],
  ["25F", "亚利桑那州和马萨诸塞州都有名为 Sandwich 的城镇。\nYàlìsāngnà zhōu hé Mǎsàzhūsāizhōu dōu yǒu míng wéi Sandwich de chéngzhèn."],
  ["26F", "奶牛在完全安静的环境下会产出更多牛奶。\nNǎiniú zài wánquán ānjìng de huánjìng xià huì chǎnchū gèng duō niúnǎi."],
  ["27F", "蒙大拿州不实行夏令时。\nMěngdàná zhōu bù shíxíng xiàlìngshí."],
  ["28F", "人体一半的红细胞每三天就会更新。\nRéntǐ yíbàn de hóngxìbāo měi sān tiān jiù huì gēngxīn."],
  ["29F", "血液约占人体体重的11%。\nXuèyè yuē zhàn réntǐ tǐzhòng de bǎifēn zhī shíyī."],
  ["30F", "没有任何鱼类能够在陆地上行走。\nMéiyǒu rènhé yúlèi nénggòu zài lùdì shàng xíngzǒu."],
  ["31F", "水母的身体中超过70%是水。\nShuǐmǔ de shēntǐ zhōng chāoguò qībǎifēnzhī shì shuǐ."],
  ["32F", "一只海星一次可产出约500万个卵。\nYì zhī hǎixīng yí cì kě chǎnchū yuē wǔ bǎi wàn gè luǎn."],
  ["33F", "水母有两颗心脏。\nShuǐmǔ yǒu liǎng kē xīnzàng."],
  ["34F", "汽车是在交通信号灯之前发明的。\nQìchē shì zài jiāotōng xìnhàodēng zhīqián fāmíng de."],
  ["35F", "打喷嚏时心脏会短暂停止跳动。\nDǎ pēntì shí xīnzàng huì duǎnzàn tíngzhǐ tiàodòng."],
  ["36F", "高尔夫球是在网球之前发明的。\nGāo'ěrfūqiú shì zài wǎngqiú zhīqián fāmíng de."],
  ["37F", "洗衣机是在洗碗机之前发明的。\nXǐyījī shì zài xǐwǎnjī zhīqián fāmíng de."],
  ["38F", "在殖民时期，只有上层阶级才吃龙虾。\nZài zhímín shíqī, zhǐyǒu shàngcéng jiējí cái chī lóngxiā."],
  ["39F", "宾夕法尼亚州的哈里斯堡是唯一没有麦当劳的美国州府。\nBīnxīfǎníyà zhōu de Hālǐsībǎo shì wéiyī méiyǒu Màidāngláo de Měiguó zhōufǔ."],
  ["40F", "特拉华州从未批准第十八修正案（禁酒令）。\nTèlāhuá zhōu cóngwèi pīzhǔn dì shíbā xiūzhèng'àn jǐnjiǔlìng."],
  ["41F", "密西西比州的建州纪念日是在情人节。\nMìxīxībǐ zhōu de jiànzhōu jìniànrì shì zài Qíngrénjié."],
  ["42F", "骆驼每只眼睛有四层眼睑。\nLuòtuó měi zhī yǎnjing yǒu sì céng yǎnjiǎn."],
  ["43F", "儿童在冬天长得更快。\nÈrtóng zài dōngtiān zhǎng de gèng kuài."],
  ["44F", "金星逆时针旋转。\nJīnxīng nìshízhēn xuánzhuǎn."],
  ["45F", "台湾是唯一国旗不是长方形的国家。\nTáiwān shì wéiyī guóqí bú shì chángfāngxíng de guójiā."],
  ["46F", "猫头鹰看不见蓝色。\nMātóuyīng kànbujiàn lánsè."],
  ["47F", "法国的陆地面积是哥伦比亚的两倍。\nFǎguó de lùdì miànjī shì Gēlúnbǐyà de liǎng bèi."],
  ["48F", "英语是美国的官方语言。\nYīngyǔ shì Měiguó de guānfāng yǔyán."],
  ["49F", "鸵鸟的眼睛有大脑的一半大。\nTuóniǎo de yǎnjing yǒu dànǎo de yíbàn dà."],
  ["50F", "杰拉尔德·福特是第一位出生在医院的美国总统。\nJiélā'ěrdé·Fútè shì dì yī wèi chūshēng zài yīyuàn de Měiguó zǒngtǒng."],
  ["51F", "詹姆斯·门罗是最矮的美国总统。\nZhānmǔsī·Ménluó shì zuì ǎi de Měiguó zǒngtǒng."],
  ["52F", "有四位美国总统被授予荣誉爵士称号。\nYǒu sì wèi Měiguó zǒngtǒng bèi shòuyǔ róngyù juéshì chēnghào."],
  ["53F", "变色龙的舌头可以伸展到身体长度的四倍。\nBiànsèlóng de shétou kěyǐ shēnzhǎn dào shēntǐ chángdù de sì bèi."],
  ["54F", "美洲豹是唯一不能收回爪子的猫科动物。\nMěizhōubào shì wéiyī bùnéng shōuhuí zhuǎzi de māokēdòngwù."],
  ["55F", "大肠大约有7英尺长。\nDàcháng dàyuē yǒu qī yīngchǐ cháng."],
  ["56F", "第一批火车在1690年代开始运行。\nDì yī pī huǒchē zài yīliùjiǔlíng niándài kāishǐ yùnxíng."],
  ["57F", "第一台录像机（VCR）制造于1973年。\nDì yī tái lùxiàngjī (VCR) zhìzào yú yījiǔqīsān nián."],
  ["58F", "世界上大约7%的水是淡水。\nShìjiè shàng dàyuē bǎifēn zhī qī de shuǐ shì dànshuǐ."],
  ["59F", "在古埃及，一码等于一个成年男子双臂展开的长度。\nZài Gǔ'āijí, yì mǎ děngyú yí gè chéngnián nánzǐ shuāngbì zhǎnkāi de chángdù."],
  ["60F", "蓝鲸是有史以来地球上第二大的动物。\nLánjīng shì yǒushǐ yǐlái dìqiú shàng dì èr dà de dòngwù."],
  ["61F", "绦虫最长可达200英尺。\nTāochóng zuìcháng kě dá èrbǎi yīngchǐ."],
  ["62F", "恒星中心的温度可超过华氏7500万度。\nHéngxīng zhōngxīn de wēndù kě chāoguò Huáshì qīqiānwǔbǎi wàn dù."],
  ["63F", "德国是第一个在战争中使用潜艇的国家。\nDéguó shì dì yī gè zài zhànzhēng zhōng shǐyòng qiántǐng de guójiā."],
  ["64F", "只有雄性蚊子会叮咬。\nZhǐyǒu xióngxìng wénzi huì dīngyǎo."],
  ["65F", "虾的心脏位于腹部。\nXiā de xīnzàng wèiyú fùbù."],
  ["66F", "委内瑞拉目前是世界上谋杀率最高的国家。\nWěinèiruìlā mùqián shì shìjiè shàng móushālǜ zuìgāo de guójiā."],
  ["67F", "男性眨眼的频率比女性高。\nNánxìng zhǎyǎn de pínlǜ bǐ nǚxìng gāo."],
  ["68F", "木星的质量是地球的400多倍。\nMùxīng de zhìliàng shì dìqiú de sìbǎi duō bèi."]
];

let trial_objects = [
  ...true_sentences.map(([code, stimulus]) => ({
    code,
    stimulus,
    condition: "true"
  })),
  ...false_sentences.map(([code, stimulus]) => ({
    code,
    stimulus,
    condition: "false"
  }))
];
